### ISSUE TITLE
There was a problem evaluating your answer, please try again later.

### ISSUE THREAD

**Issue by smac89** [scala-exercises/scala-exercises#613]
I get this error message when running this example from psql, and it happens whenever I enter something in the boxes and press enter or click the run button:

```bash
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
fr.hmil.roshttp.HttpNetworkError: java.net.ConnectException: Connection refused (Connection refused)
	at fr.hmil.roshttp.HttpDriver$$anonfun$send$1.apply(HttpDriver.scala:23) ~[roshttp_2.11-1.1.0.jar:1.1.0]
	at fr.hmil.roshttp.HttpDriver$$anonfun$send$1.apply(HttpDriver.scala:16) ~[roshttp_2.11-1.1.0.jar:1.1.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_121]
[error] application - 

! @72mk65cl7 - Internal server error, for (POST) [/exercises/sections/std_lib/asserts/evaluate] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[HttpNetworkError: java.net.ConnectException: Connection refused (Connection refused)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:277) [play-netty-server_2.11-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.8.jar:2.4.8]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346) [scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345) [scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.8.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.8.jar:na]
Caused by: fr.hmil.roshttp.HttpNetworkError: java.net.ConnectException: Connection refused (Connection refused)
	at fr.hmil.roshttp.HttpDriver$$anonfun$send$1.apply(HttpDriver.scala:23) ~[roshttp_2.11-1.1.0.jar:1.1.0]
	at fr.hmil.roshttp.HttpDriver$$anonfun$send$1.apply(HttpDriver.scala:16) ~[roshttp_2.11-1.1.0.jar:1.1.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_121]
```

Screenshot if it helps:
![screenshot from 2017-01-19 23-36-41](https://cloud.githubusercontent.com/assets/8305511/22137367/3a4a933a-dea0-11e6-8448-6dadf7eacb2d.png)

**Comment by juanpedromoreno** [comment]
Hi @smac89 ,

Did you run the evaluator locally? https://github.com/scala-exercises/evaluator#run-from-sources (port 8080 by default).

If you did, please, let us know to look at your issue. Thx.

**Comment by Arpana-786** [comment]
I am geting on scala exercise after run :
There was a problem evaluating your answer, please try again later.
