### ISSUE TITLE
Exception sass

### ISSUE THREAD

**Issue by danielgoncalvesti** [scala-exercises/scala-exercises#680]
## Problem

I've tried to run in my local computer but I got this error. Has anyone already gotten this same log?

`[info] Sass compiling on 1 source(s)
[info] Packaging /Users/danielgoncalves/devel/scala-exercises/compiler/target/scala-2.11/exercise-compiler_2.11-0.4.0-SNAPSHOT.jar ...
[info] Done packaging.
java.lang.Exception: 
Sass compiler: Unknown error, try running sass directly
File: /Users/danielgoncalves/devel/scala-exercises/server/app/assets/stylesheets/main.scss
Line: 0 Col: 0
	at sass.SassCompiler$.compile(SassCompiler.scala:29)
	at sass.SbtSass$$anonfun$5$$anonfun$6$$anonfun$7.apply(SbtSass.scala:55)
	at sass.SbtSass$$anonfun$5$$anonfun$6$$anonfun$7.apply(SbtSass.scala:43)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sass.SbtSass$$anonfun$5$$anonfun$6.apply(SbtSass.scala:43)
	at sass.SbtSass$$anonfun$5$$anonfun$6.apply(SbtSass.scala:39)
	at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
	at sass.SbtSass$$anonfun$5.apply(SbtSass.scala:38)
	at sass.SbtSass$$anonfun$5.apply(SbtSass.scala:33)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (server/web-assets:sass) java.lang.Exception: 
[error] Sass compiler: Unknown error, try running sass directly
[error] File: /Users/danielgoncalves/devel/scala-exercises/server/app/assets/stylesheets/main.scss
[error] Line: 0 Col: 0
[error] Total time: 150 s, completed May 5, 2018 11:33:39 PM`

## Solution

Install the Ruby gem `sass` and not the npm `sass`.

**Comment by FRosner** [comment]
I have no clue. Have you tried running `sass` directly? Which commit did you check out? Does it also happen for other commits / tags?

**Comment by danielgoncalvesti** [comment]
Yes, I’ve already checked `sass` in terminal and I got ok. I’m gonna try another tag.

**Comment by jmjava** [comment]
is there a fix for this?  I am getting the same error now

**Comment by FRosner** [comment]
Thanks @jmjava. Is there a piece of documentation which should get updated to make this more obvious?

**Comment by jmjava** [comment]
Frank,  I think the link takes you to a page that is focused on the node version.  Maybe link to the Ruby version directly?




Get Outlook for Android







On Sun, Jul 22, 2018 at 10:57 AM -0400, "Frank Rosner" <notifications@github.com> wrote:












Thanks @jmjava. Is there a piece of documentation which should get updated to make this more obvious?
